CREATE DATABASE IF NOT EXISTS online_shopping;
USE online_shopping;
DROP TABLE IF EXISTS DELIVERY;
DROP TABLE IF EXISTS PAYMENT;
DROP TABLE IF EXISTS ORDER_ITEMS;
DROP TABLE IF EXISTS ORDERS;
DROP TABLE IF EXISTS CART;
DROP TABLE IF EXISTS PRODUCT;
DROP TABLE IF EXISTS CATEGORY;
DROP TABLE IF EXISTS CUSTOMER;

CREATE TABLE CUSTOMER(Customer_ID INT AUTO_INCREMENT PRIMARY KEY,Customer_Name VARCHAR(100) NOT NULL,Email VARCHAR(100) NOT NULL UNIQUE,Phone VARCHAR(20),Address VARCHAR(255));
CREATE TABLE CATEGORY(Category_ID INT AUTO_INCREMENT PRIMARY KEY,Category_Name VARCHAR(100) NOT NULL UNIQUE);
CREATE TABLE PRODUCT(Product_ID INT AUTO_INCREMENT PRIMARY KEY,Product_Name VARCHAR(150) NOT NULL,Category_ID INT NOT NULL,Price DECIMAL(10,2) NOT NULL,Stock INT NOT NULL DEFAULT 0,FOREIGN KEY(Category_ID) REFERENCES CATEGORY(Category_ID));
CREATE TABLE CART(Cart_ID INT AUTO_INCREMENT PRIMARY KEY,Customer_ID INT NOT NULL,Product_ID INT NOT NULL,Quantity INT NOT NULL,FOREIGN KEY(Customer_ID) REFERENCES CUSTOMER(Customer_ID),FOREIGN KEY(Product_ID) REFERENCES PRODUCT(Product_ID));
CREATE TABLE ORDERS(Order_ID INT AUTO_INCREMENT PRIMARY KEY,Customer_ID INT NOT NULL,Order_Date DATE NOT NULL,Total_Amount DECIMAL(10,2) NOT NULL,Order_Status VARCHAR(50) NOT NULL DEFAULT 'Placed',FOREIGN KEY(Customer_ID) REFERENCES CUSTOMER(Customer_ID));
CREATE TABLE ORDER_ITEMS(Order_Item_ID INT AUTO_INCREMENT PRIMARY KEY,Order_ID INT NOT NULL,Product_ID INT NOT NULL,Quantity INT NOT NULL,Price DECIMAL(10,2) NOT NULL,FOREIGN KEY(Order_ID) REFERENCES ORDERS(Order_ID),FOREIGN KEY(Product_ID) REFERENCES PRODUCT(Product_ID));
CREATE TABLE PAYMENT(Payment_ID INT AUTO_INCREMENT PRIMARY KEY,Order_ID INT NOT NULL,Payment_Date DATE NOT NULL,Payment_Method VARCHAR(50) NOT NULL,Payment_Status VARCHAR(50) NOT NULL,FOREIGN KEY(Order_ID) REFERENCES ORDERS(Order_ID));
CREATE TABLE DELIVERY(Delivery_ID INT AUTO_INCREMENT PRIMARY KEY,Order_ID INT NOT NULL,Delivery_Address VARCHAR(255) NOT NULL,Delivery_Date DATE NULL,Delivery_Status VARCHAR(50) NOT NULL,FOREIGN KEY(Order_ID) REFERENCES ORDERS(Order_ID));

INSERT INTO CATEGORY(Category_Name) VALUES ('Electronics'),('Clothing'),('Books'),('Home & Kitchen');
INSERT INTO PRODUCT(Product_Name,Category_ID,Price,Stock) VALUES
('Wireless Headphones',1,1499.00,20),('Smart Watch',1,2499.00,15),('Cotton T-Shirt',2,599.00,30),
('DBMS Fundamentals Book',3,799.00,25),('Coffee Mug',4,299.00,40),('Laptop Backpack',4,1299.00,18);
INSERT INTO CUSTOMER(Customer_Name,Email,Phone,Address) VALUES ('Demo Customer','demo@example.com','9999999999','College Road');
